#!/usr/bin/env bash
# color-match.sh - Match video color to a reference frame using color_matcher.
#                  Extracts the middle frame, computes a color transfer, bakes
#                  it into a 3D .cube LUT, then applies the LUT to the full clip.
#
# Usage: color-match.sh <input.mp4> <reference.jpg> <output.mp4> [--method mkl]
#   --method : mkl (default) | reinhard | mvgd | hm

source "$(dirname "$0")/lib/common.sh"
require_ffmpeg

[[ $# -ge 3 ]] || die "Usage: $(basename "$0") <input.mp4> <reference.jpg> <output.mp4> [--method mkl]"

IN="$1"; REF="$2"; OUT="$3"; shift 3
METHOD="mkl"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --method) METHOD="$2"; shift 2 ;;
    *) die "Unknown flag: $1" ;;
  esac
done

[[ -f "$IN"  ]] || die "Input not found: $IN"
[[ -f "$REF" ]] || die "Reference not found: $REF"
mkdir -p "$(dirname "$OUT")"

VENV="$VIDEO_ROOT/_SYSTEM/.venv"
[[ -x "$VENV/bin/python" ]] || die "BMP Python venv not found at $VENV. Run: python3 -m venv $VENV && $VENV/bin/pip install color-matcher"

# Validate method
case "$METHOD" in
  mkl|reinhard|mvgd|hm) ;;
  *) die "Unknown method: $METHOD. Choose from: mkl reinhard mvgd hm" ;;
esac

TMP=$(mktemp -d -t bmp_colormatch.XXXX)
FRAME_SRC="$TMP/src_frame.png"
LUT_FILE="$TMP/colormatch.cube"

log "Extracting middle frame from $IN ..."
DURATION=$(probe_duration "$IN")
MID=$(echo "$DURATION" | awk '{printf "%.3f", $1/2}')
ffmpeg -hide_banner -loglevel error -y \
  -ss "$MID" -i "$IN" -vframes 1 "$FRAME_SRC"

[[ -f "$FRAME_SRC" ]] || die "Failed to extract middle frame"

log "Computing color transfer (method=$METHOD) and generating 3D LUT ..."
"$VENV/bin/python" - <<PYEOF
import sys
from pathlib import Path
import numpy as np

try:
    from color_matcher import ColorMatcher
    from color_matcher.io_handler import load_img_file
except ImportError:
    print("[ERR]  color_matcher not installed. Run: pip install color-matcher", file=sys.stderr)
    sys.exit(1)

src  = load_img_file("$FRAME_SRC")
ref  = load_img_file("$REF")

cm = ColorMatcher(method="$METHOD")
# We only need the matcher internals — compute stats against the reference
# then bake into a 3D LUT grid (33x33x33)
LUT_SIZE = 33

# Build identity LUT coordinates in [0,1]
lin = np.linspace(0, 1, LUT_SIZE, dtype=np.float32)
r, g, b = np.meshgrid(lin, lin, lin, indexing='ij')
identity = np.stack([r, g, b], axis=-1).reshape(-1, 3)  # (N, 3)

# Fit matcher on source/reference images then transform identity grid
src_f = src.astype(np.float32) / 255.0
ref_f = ref.astype(np.float32) / 255.0

# Use full image pixels as training data
src_px = src_f.reshape(-1, 3)
ref_px = ref_f.reshape(-1, 3)

# Apply color matching to the identity LUT grid
identity_u8 = (identity * 255).astype(np.uint8).reshape(1, -1, 3)
ref_u8      = (ref_px   * 255).astype(np.uint8).reshape(1, -1, 3)

cm_instance = ColorMatcher(method="$METHOD")
mapped_u8 = cm_instance.transfer(src=identity_u8, ref=ref_u8, out_type='uint8')
mapped = mapped_u8.reshape(-1, 3).astype(np.float32) / 255.0

# Write .cube file
with open("$LUT_FILE", "w") as f:
    f.write("# Generated by BMP color-match.sh (method: $METHOD)\n")
    f.write(f"LUT_3D_SIZE {LUT_SIZE}\n\n")
    for row in mapped:
        r_, g_, b_ = np.clip(row, 0.0, 1.0)
        f.write(f"{r_:.6f} {g_:.6f} {b_:.6f}\n")

print(f"[OK]  LUT written: $LUT_FILE  ({len(mapped)} entries)")
PYEOF

[[ $? -eq 0 ]] || die "Python color transfer failed"
[[ -f "$LUT_FILE" ]] || die "LUT file was not created"

log "Applying LUT to video → $OUT ..."
ffmpeg -hide_banner -loglevel error -stats -y \
  -i "$IN" \
  -vf "lut3d='${LUT_FILE}'" \
  -c:v libx264 -preset medium -crf 18 -pix_fmt yuv420p \
  -c:a copy \
  -movflags +faststart \
  "$OUT"

rm -rf "$TMP"
ok "Color-matched: $OUT (method=$METHOD, reference=$(basename "$REF"))"
